import localFont from "next/font/local";
import '@fortawesome/fontawesome-free/css/all.min.css';
import "./globals.css";
import Header from "../component/Header";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Text to Speak",
  description: "Generated by Text to Speak",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
