export const languageMap = new Map([
  ["ar-AE", "Arabic (Gulf)"],
  ["en-ZA", "Afrikaans (English South Africa)"],
  ["cmn-CN", "Chinese (Simplified, China)"],
  ["da-DK", "Danish"],
  ["nl-NL", "Dutch (Netherlands)"],
  ["en-US", "English (United States)"],
  ["fr-CA", "French (Canada)"],
  ["fi-FI", "Finnish"],
  ["fr-FR", "French (France)"],
  ["de-DE", "German (Germany)"],
  ["hi-IN", "Hindi"],
  ["it-IT", "Italian"],
  ["is-IS", "Icelandic"],
  ["ja-JP", "Japanese"],
  ["ko-KR", "Korean"],
  ["pt-PT", "Portuguese (Portugal)"],
  ["pl-PL", "Polish"],
  ["ru-RU", "Russian"],
  ["ro-RO", "Romanian"],
  ["es", "Spanish (International)"],
  ["es-US", "Spanish (Latin America)"],
  ["es-ES", "Spanish (Spain)"],
  ["tr-TR", "Turkish"]
]);

export const pollyandTranslatorLanguageMap = new Map([
  ["ar-AE", "ar"],
  ["en-ZA", "af"],
  ["cmn-CN", "zh"],
  ["da-DK", "da"],
  ["nl-NL", "nl"],
  ["en-US", "en"],
  ["fr-CA", "fr-CA"],
  ["fi-FI", "fi"],
  ["fr-FR", "fr"],
  ["de-DE", "de"],
  ["hi-IN", "hi"],
  ["it-IT", "it"],
  ["is-IS", "is"],
  ["ja-JP", "ja"],
  ["ko-KR", "ko"],
  ["pt-PT", "pt-PT"],
  ["pl-PL", "pl"],
  ["ru-RU", "ru"],
  ["ro-RO", "ro"],
  ["es", "es"],
  ["es-US", "es-MX"],
  ["es-ES", "es"],
  ["tr-TR", "tr"]
]);